import type { Author, CategoryId, ImageMeta, Note, NoteCategory, Scene } from '../types';

export const CATEGORIES: { id: CategoryId; label: string }[] = [
  { id: 'recommend', label: '推荐' },
  { id: 'travel', label: '旅行' },
  { id: 'food', label: '美食' },
  { id: 'home', label: '家居' },
  { id: 'pets', label: '萌宠' },
  { id: 'city', label: '城市' },
];

const SCENE_CATEGORY: Record<Scene, NoteCategory> = {
  mountain: 'travel', sea: 'travel', coffee: 'food', dessert: 'food', plant: 'home', flowers: 'home', cat: 'pets', city: 'city',
};

const img = (file: string, height: number): ImageMeta => {
  const scene = file.split('-')[1] as Scene;
  return { file: `images/${file}`, width: 600, height, scene, category: SCENE_CATEGORY[scene] };
};

/** Local illustrations generated by scripts/generate-images.mjs (600px wide, different heights). */
export const IMAGES: ImageMeta[] = [
  img('01-mountain-dawn.svg', 760), img('02-mountain-lake.svg', 600), img('03-mountain-dusk.svg', 900),
  img('04-sea-tropic.svg', 800), img('05-sea-sunset.svg', 680), img('06-sea-mint.svg', 450),
  img('07-coffee-oak.svg', 750), img('08-coffee-slate.svg', 600), img('09-coffee-rose.svg', 820),
  img('10-plant-sage.svg', 880), img('11-plant-cream.svg', 640), img('12-plant-blue.svg', 760),
  img('13-city-night.svg', 840), img('14-city-neon.svg', 620), img('15-city-blue.svg', 980),
  img('16-dessert-berry.svg', 700), img('17-dessert-matcha.svg', 820), img('18-dessert-choco.svg', 600),
  img('19-flowers-tulip.svg', 860), img('20-flowers-sun.svg', 700), img('21-flowers-lilac.svg', 780),
  img('22-cat-ginger.svg', 720), img('23-cat-gray.svg', 840), img('24-cat-snow.svg', 640),
];

const AUTHOR_NAMES = [
  '晚风同学', '橘子汽水', '山野来信', '一颗柠檬', '阿离不加班', '小鹿乱撞', '奶油桃桃', '周末去哪儿',
  '咖啡续命中', '猫咪观察员', '在逃公主', '城市漫游者', '植物系女孩', '甜品研究所', '海边的卡卡', '慢慢生活家',
];
const AUTHOR_COLORS = ['#fe2c55', '#ff8a3d', '#f5b82e', '#3cc48d', '#2bb3c0', '#4f8df7', '#7a6ff0', '#c86bfa', '#ff6fa8', '#5c6b7a'];
export const AUTHORS: Author[] = AUTHOR_NAMES.map((name, i) => ({ id: `u${i + 1}`, name, color: AUTHOR_COLORS[(i * 7) % AUTHOR_COLORS.length] }));

const TITLES: Record<Scene, string[]> = {
  mountain: [
    '人生必去的一次雪山徒步，日照金山太震撼了', '第一次看到这么透亮的湖水，像打翻了调色盘', '徒步路线分享：难度适中、出片率超高',
    '在山里住了三天，手机都不想看', '凌晨四点爬山看日出，值了！', '山野露营清单｜新手照着带就够了',
    '高原湖泊的蓝，真的不需要滤镜', '周末两天一夜，去山里吹吹风', '云海翻涌的那一刻，所有疲惫都消失了',
    '小众徒步线路，一路上几乎没遇到人', '傍晚的山谷，被晚霞染成了紫色', '登山新手第一次登顶，记录一下',
  ],
  sea: [
    '小众海岛攻略｜人少景美，三天两晚超详细', '跟着落日去旅行，这片海边值得住一晚', '原来晚霞真的会有粉紫色',
    '海边露营保姆级清单，照着带就对了', '一个人的旅行｜去看看没见过的海', '椰子树下发呆的一下午',
    '这片沙滩的水清得能看见小鱼', '海边小镇 citywalk，每个转角都是夏天', '浮潜初体验！终于见到了海龟',
    '把夏天装进相机里：海边拍照姿势合集', '日落时分的海，温柔得不像话', '冬天去海边，人少风大但很治愈',
  ],
  coffee: [
    '在家也能做的拿铁拉花，零失败教程来了', '周末探店｜藏在巷子里的宝藏咖啡馆', '手冲咖啡入门：器具、豆子和水温全攻略',
    '把咖啡馆搬回家，打工人的周末仪式感', '每天一杯燕麦拿铁，续命成功', '咖啡豆怎么选？一篇讲清楚产区和烘焙度',
    '桌搭分享｜我的晨间咖啡角', '爱心拉花练了一个月，终于成型了', '这家店的 dirty 真的绝，回头客预定',
    '冷萃咖啡的正确打开方式', '下雨天最适合找家咖啡店坐一下午', '平价咖啡器具推荐，学生党也能入',
  ],
  dessert: [
    '草莓奶油蛋糕｜第一次做就成功的配方', '抹茶控必收！这家千层真的绝了', '低卡甜品也能好吃到哭，附详细做法',
    '巧克力爱好者的天堂，甜而不腻', '生日蛋糕自己做，颜值不输蛋糕店', '一人食｜十分钟搞定的暖心下午茶',
    '烘焙小白也能成功的戚风蛋糕', '周末甜品店打卡，每一块都想带走', '抹茶红豆蛋糕卷，层次感满满',
    '奶油裱花技巧分享，新手也能学会', '下午茶的快乐就是这么简单', '把草莓季吃到最后一口',
  ],
  plant: [
    '出租屋改造｜500 元打造治愈系小窝', '新手养绿植，这 5 种真的很难养死', '阳台花园进度分享，越来越像样了',
    '窗边的绿意，是一天里最治愈的角落', '龟背竹爆新叶了！分享养护心得', '极简收纳思路，桌面终于清爽了',
    '绿植浇水的正确频率，别再养死了', '奶油风客厅软装清单，平价也能出效果', '给植物换盆全过程记录',
    '办公桌上的小绿植，上班心情都变好了', '养了三年的绿萝，已经爬满整面墙', '植物角布置｜一角就有大氛围',
  ],
  flowers: [
    '春天的第一束郁金香，家里瞬间有了氛围感', '向日葵花束的保鲜小技巧，多开一周', '插花小白也能学会的三种搭配',
    '每周给自己买一束花，生活需要一点浪漫', '花瓶选得好，插花不用愁', '紫色系花束，温柔又高级',
    '周末逛花市，十块钱抱回一大束', '鲜花延长花期的 6 个小方法', '餐桌上的一束花，让吃饭都变得认真',
    '郁金香会在花瓶里继续长高，你知道吗', '自己包的花束送朋友，被夸爆了', '花艺入门：配色思路分享',
  ],
  cat: [
    '我家猫主子的一天，真的太会享受了', '新手养猫必看！这些用品千万别乱买', '被小猫的眼神杀到了…',
    '猫咪玩毛线球的样子也太可爱了吧', '记录小猫从巴掌大到现在的变化', '猫咪挑食怎么办？亲测有效的几个方法',
    '谁能拒绝一只软乎乎的小白猫', '橘猫的饭量，果然名不虚传', '猫咪洗澡全过程，全程大型反抗现场',
    '猫咪的迷惑行为大赏', '给猫做的生日蛋糕，它居然只舔了一口', '下班回家，猫在门口等我',
  ],
  city: [
    '城市夜景机位分享｜手机也能拍出大片', '下班路上的霓虹，城市也有温柔的一面', '在 38 楼看了一整晚的灯火',
    'Citywalk 路线｜一天逛完老城区的宝藏街道', '雨夜的城市，适合一个人慢慢走', '赛博朋克感拉满的夜晚，随手一拍都是壁纸',
    '城市观景台合集，第三个人少景美', '加班到深夜，抬头看见的城市星空', '夜跑路线推荐，沿江的风太舒服了',
    '月亮挂在高楼之间的那一刻', '蓝调时刻的城市，比白天更好看', '城市夜景拍摄参数分享',
  ],
};

const DESCS: Record<NoteCategory, string[]> = {
  travel: ['出发前做了很多功课，真正站在那里的时候还是被震撼到了。', '路线、交通和住宿都整理在下面了，收藏起来慢慢看。', '建议避开节假日，清晨和傍晚的光线最好看。', '记得带好防晒和外套，早晚温差很大。', '一路上遇到的人都很友善，下次还想再来。', '照片完全没有调色，现场比照片更好看。'],
  food: ['步骤其实很简单，关键是耐心和一点点小技巧。', '甜度可以按自己口味调整，冷藏一晚口感更好。', '环境安静，适合带本书坐一下午。', '材料清单放在最后一张，照着做基本不会翻车。', '价格很友好，人均不到五十。', '第一次做的时候失败了两次，总结了几个关键点。'],
  home: ['预算不多，但每一样都是认真挑过的。', '记得定期修剪和换水，花期能延长不少。', '把喜欢的东西放在看得见的地方，心情会变好。', '光照充足的位置最适合，避免正午暴晒。', '好物清单整理在评论区啦。', '慢慢布置的过程本身就很治愈。'],
  pets: ['每天下班回家看到它，所有烦恼都没有了。', '养宠之后才知道，原来陪伴是双向的。', '用品清单放在评论区，欢迎交流～', '它今天又解锁了新的睡姿。', '建议新手先做好功课再接猫回家。', '猫咪的快乐真的很简单。'],
  city: ['城市的夜晚总有一些意想不到的温柔。', '机位和参数都写在下面了，器材不重要，耐心最重要。', '走累了就找家小店坐坐，看看来往的人。', '这条路线全程步行大概三小时。', '日落后二十分钟的蓝调时刻最出片。', '记得避开晚高峰，人会少很多。'],
};

const TAGS: Record<NoteCategory, string[]> = {
  travel: ['旅行', '徒步', '海边', '风景', '周末去哪儿', '小众景点'],
  food: ['美食', '咖啡', '甜品', '探店', '烘焙', '下午茶'],
  home: ['家居', '绿植', '鲜花', '软装', '出租屋改造', '收纳'],
  pets: ['萌宠', '猫咪', '养猫日常', '新手养猫'],
  city: ['城市', '夜景', 'Citywalk', '摄影', '霓虹'],
};

export const COMMENTS = [
  '太好看了吧，已收藏！', '求同款链接～', '看完立刻想出发', '博主的审美真的在线', '这个配色好治愈', '学到了，周末就试试', '第三张绝了', '蹲一个详细攻略',
];

const NOTE_CATEGORIES: NoteCategory[] = ['travel', 'food', 'home', 'pets', 'city'];

const mulberry32 = (seed: number) => () => {
  seed = (seed + 0x6d2b79f5) | 0;
  let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
const pick = <T,>(r: () => number, list: T[]) => list[Math.floor(r() * list.length)];
const pickTwo = <T,>(r: () => number, list: T[]): [T, T] => {
  const a = Math.floor(r() * list.length);
  const b = (a + 1 + Math.floor(r() * (list.length - 1))) % list.length;
  return [list[a], list[b]];
};

/** Every 23rd note intentionally points at a missing file so the default-image fallback can be seen. */
export const BROKEN_EVERY = 23;

/** Deterministic mock note: the same (feed, seed, index) always yields the same content, so ids can be resolved on reload. */
export function makeNote(feed: CategoryId, seed: number, index: number): Note {
  const catIndex = Math.max(0, CATEGORIES.findIndex((c) => c.id === feed));
  const r = mulberry32(seed * 100003 + index * 7919 + catIndex * 31);
  const category = feed === 'recommend' ? pick(r, NOTE_CATEGORIES) : feed;
  const image = pick(r, IMAGES.filter((m) => m.category === category));
  const roll = r();
  const likes = roll < 0.55 ? Math.floor(8 + r() * 1800) : roll < 0.9 ? Math.floor(2000 + r() * 18000) : Math.floor(20000 + r() * 130000);
  const tags = [...new Set([pick(r, TAGS[category]), pick(r, TAGS[category]), pick(r, TAGS[category])])];
  const broken = index % BROKEN_EVERY === BROKEN_EVERY - 1;
  return {
    id: `${feed}-${seed}-${index}`,
    title: pick(r, TITLES[image.scene]),
    desc: pickTwo(r, DESCS[category]).join(''),
    image: broken ? image.file.replace('images/', 'images/missing/') : image.file,
    width: image.width,
    height: image.height,
    author: pick(r, AUTHORS),
    likes,
    collects: Math.floor(likes * (0.2 + r() * 0.5)),
    comments: Math.floor(likes * (0.02 + r() * 0.08)),
    category,
    tags,
    createdAt: Date.UTC(2026, 8, 30) - Math.floor(r() * 120) * 86400000,
  };
}

export function parseNoteId(id: string): { feed: CategoryId; seed: number; index: number } | null {
  const m = /^(recommend|travel|food|home|pets|city)-(\d+)-(\d+)$/.exec(id);
  return m ? { feed: m[1] as CategoryId, seed: Number(m[2]), index: Number(m[3]) } : null;
}
